# Generated by Django 3.1 on 2020-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=1024)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('photo', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('fashion', 'Fashion'), ('appliances', 'Appliances'), ('automotive', 'Automotive'), ('collectibles', 'Collectibles'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('kitchen', 'Kitchen'), ('jewelry', 'Jewelry'), ('software', 'Software'), ('toys', 'Toys')], max_length=64)),
            ],
        ),
    ]
