# Generated by Django 3.1 on 2020-08-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200819_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='cost',
            new_name='currentCost',
        ),
    ]
