# Generated by Django 3.1 on 2020-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200825_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='last',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
