# Generated by Django 3.1 on 2020-08-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200825_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
