# Generated by Django 3.1 on 2020-08-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200825_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('fashion', 'Fashion'), ('beauty', 'Beauty'), ('appliances', 'Appliances'), ('automotive', 'Automotive'), ('collectibles', 'Collectibles'), ('music', 'Music'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('kitchen', 'Kitchen'), ('jewelry', 'Jewelry'), ('software', 'Software'), ('toys', 'Toys')], max_length=64),
        ),
    ]
